Dr 22 09 miracle monk
BetaMasaheft/Authority-Files pull request #24
Opened 2022-09-06 13:00 UTC by GueshSol

I created a new art theme on one of the miniatures of the thirty-three narrations of the Ethiopian miracles of Mary. I would be very grateful for your review on the art theme I submitted.

2022-09-07 07:38 UTC, thea-m requested changes

2022-09-07 07:38 UTC, thea-m commented on ArtThemes/AT1145MMGarment.xml
> +                <editor key="DR"/>
I think you should also add yourself as an editor, as you carried out all meaningful edits in this record

2022-09-08 11:40 UTC, thea-m approved these changes

2022-09-08 11:42 UTC, merged

2022-09-09 14:28 UTC, gnizla commented
Sorry for slow response and thanks for your work: looks great to me, I might have written "monk to whom" but you decide! Keep up the hard work!