Create AT1147CaliphAtrib.xml
BetaMasaheft/Authority-Files pull request #30
Opened 2023-05-26 12:06 UTC by GueshSol

2023-05-26 13:30 UTC, thea-m requested changes
Very good! I just added some suggestions

2023-05-26 13:30 UTC, thea-m commented on new/AT1147CaliphAtrib.xml
> +                <title>A Caliph from Ātrib tries to destroy a Church</title>
ʾAtrib

2023-05-26 13:30 UTC, thea-m commented on new/AT1147CaliphAtrib.xml
> +                    destroy a Church in Ātrib; second, <persName ref="PRS6819Mary"/>"/> appearing to the
ʾAtrib

2023-05-26 13:30 UTC, thea-m commented on new/AT1147CaliphAtrib.xml
> +                    destroy a Church in Ātrib; second, <persName ref="PRS6819Mary"/>"/> appearing to the
`<persName ref="PRS6819Mary"/>"/>` - here there is one `"/>` too much

2023-05-26 13:30 UTC, thea-m commented on new/AT1147CaliphAtrib.xml
> +                    Caliph (who was in sleep) to order his agent to stop the destruction of the
"who was asleep" would be better, I think

2023-05-26 13:30 UTC, thea-m commented on new/AT1147CaliphAtrib.xml
> +                    fourth, the Caliph who later become believer sitting in front of the Church.</p>
"who later became a believer"

2023-06-26 15:42 UTC, thea-m commented
@GueshSol Could you please carry out the corrections in the file, so that this can be merged? Thanks a lot!

2024-09-10 07:39 UTC, eu-genia commented
@GueshSol

2024-09-11 14:23 UTC, GueshSol commented
@thea-m there seems deletion with the branch under discussion. I was trying to carry out the corrections you provided. The art ID does not appear in the art theme section or even in  the new sub-repository. I have the branch on my GitHub not deleted even after several months, but
 the branch is not in the list. What should I do?

2024-09-11 16:16 UTC, eu-genia commented
You have to switch to the branch you were working in in your GitHub desktop.
As long as the branch has not been merged you cannot see the record in the master branch.

2024-09-11 16:17 UTC, eu-genia commented
The name of the branch is `Guesh-26-23` as you can see above

2024-09-11 18:48 UTC, eu-genia commented
Dear Guesh, please switch to this branch and carry out your changes here, I will close the new pull request

2024-09-11 18:52 UTC, eu-genia commented
![image](https://github.com/user-attachments/assets/6b198e52-9462-4965-b4bd-c50c0c43ab11)

2024-09-12 12:26 UTC, eu-genia requested changes

2024-09-12 12:26 UTC, eu-genia commented on new/AT1147CaliphAtrib.xml
> +              <change who="GS" when="2024-09-12">corrected typo errors
please check the nesting, you inserted change inside of another change

2024-09-12 12:47 UTC, GueshSol commented
I see. I think I solved it. Thank you.

2024-09-12 12:55 UTC, eu-genia requested changes

2024-09-12 12:55 UTC, eu-genia commented on new/AT1147CaliphAtrib.xml
> +                    fourth, the Caliph who later become believer sitting in front of the Church.</p>
this has not been corrected

2024-09-12 12:55 UTC, eu-genia commented on new/AT1147CaliphAtrib.xml
> +            <langUsage>
always before submitting anything check in your oxygen that the document is valid (green). This document is not well formed XML
in line 55 you need the closing tag `</langUsage>`, not the opening tag

2024-09-12 13:17 UTC, GueshSol commented
I know what you said. Oxygen gives you a chance if any element is misplaced, wrongly added or omitted but for this art theme, my Oxygen application did not help me to edit the branch. I tried to fix it using an Atom app that automatically give me a chance to edit it. That's why I am unable to see some of the minor errors; I did not manage it well working using Atom for XML description.  It should work now.

2024-09-12 13:33 UTC, eu-genia approved these changes

2024-10-16 17:52 UTC, eu-genia commented
I believe this PR has not been merged, what is the reason you are closing an unmerged pull request?

2024-10-16 17:53 UTC, eu-genia commented
It was waiting to be approved by @thea-m in order to be merged.

2024-10-16 18:10 UTC, GueshSol commented
@eu-genia  I apologize for the error; I just thought it was done.

2024-10-23 07:40 UTC, thea-m approved these changes

2024-10-23 07:40 UTC, merged